name,age=(input("enter your name and age sparated by comma ").split(","))
#name,age=(input("enter your name and age saparated by space ").split())
#enter your name and age saparated by space  rmapati 23 (true)
#enter your name and age saparated by space  rmapati pandey 23 (erroe because after space entered another string)
print(name)
print(age) 